- name: Invisibles
  number: 0
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: PCMS-1
  number: 1
  fieldPlayerColors: [red, blue]
  goalkeeperColors: [blue, red]
- name: PCMS-2
  number: 2
  fieldPlayerColors: [black, white]
  goalkeeperColors: [white, black]
